### ISSUE TITLE
[BUG] Using full name instead of username

### ISSUE THREAD

**Issue by devanteweary** [luigi311/JellyPlex-Watched#137] opened 2024-01-10 20:22 UTC
**Describe the bug**
Hey! Since I updated yesterday, I noticed that everytime it runs, it shows that it's [MARK]s the same movies and episodes everytime.

**To Reproduce**
Either restart the container or let it run on schedule.

**Expected behavior**
No marking at all unless there is a true change in watch states.

**Type:**
Unraid

**Comment by devanteweary** [comment] 2024-01-10 20:31
Oh and side note, I noticed when I updated, a bunch of shows/movies that were on my Continue Watching list in Plex that fell off weeks ago were now back on that list again.

**Comment by devanteweary** [comment] 2024-01-13 17:45
Hey @luigi311 , got some more troubleshooting done... 
I think it's now using the Plex "Full name" rather than username to map to Plex.

For instance, my Plex username is DevanteWeary but full name is "Devante Weary".
Jellyfin it's simply Devante.

The logs shows this when getting to me...

`Plex: Generating watched for devante weary in library Movies`
`Jellyfin: Generating watched for devante in library Movies`

I checked logs before the update a few days ago and I get this...

`Plex: Generating watched for devanteweary in library Movies`
`Jellyfin: Generating watched for devante in library Movies`

and then at the very bottom of the log I get this in red...

`[ERROR]: devante weary None not found in Jellyfin`
`Average time: 54.35092554206494`
`Looping in 300.0'`

Also, I tried changing "DevanteWeary" to "Devante Weary" in the user mapping and it simply skips over my watch states.  
As if I don't exist.

OK hope it helps!

**Comment by devanteweary** [comment] 2024-01-13 20:56
OK you're gonna hate me... but wanted to update with some MORE troubleshooting..

I restored from an appdata restore/backup plugin restore from 01/07/2024 at about 8am...

Same issue.
So I'm thinking Plex changed something on their side.

**Comment by luigi311** [comment] 2024-01-13 21:48
I don’t store anything in appdata on unraid. Can you try the latest release. Someone found an issue with matching so maybe that will fix your issue.

**Comment by devanteweary** [comment] 2024-01-13 22:33
> I don’t store anything in appdata on unraid. Can you try the latest release. Someone found an issue with matching so maybe that will fix your issue.

Just tried the latest version again and the same exact issue.

**Comment by devanteweary** [comment] 2024-01-15 21:51
More troubleshooting:

- Removed all user mapping.
- Restarted and it synced just the accounts with the same username.
- Added only myself: { "DevanteWeary": "Devante" }
- Still did the same username people but also tried to Plex sync "Devante Weary" (which is what my **full name** is set to) and JF sync "Devante". Basically the result that has been going on.

It's like it recognizes I am mapping the right Plex account, but uses the wrong field to actually get the name in Plex.

**Comment by bexem** [comment] 2024-01-17 16:54
I had a similar issue with a specific TV show that I started rewatching a couple of days ago. I marked it as 'not watched' on Plex, and literally a few minutes later, it would set itself back as 'watched.' I tried on different clients as well.

Then, when I read about your issue and checked my shadow Jellyfin instance, I noticed that the watched status hadn't synced for a while between plex and jellyfin. I understood that it was the container, confirmed by the fact that Plex started correctly keeping track of the watched/unwatched status of that show. Oddity? It was working fine with another show that was already on deck.

**Comment by devanteweary** [comment] 2024-01-19 18:55
> can you try the :fixes image and see if that works for you. There was an issue where if there was no season number for one of the shows in your library it would cause it to fail to generate a watch list for jellyfin so it would then start marking everything in jellyfin and not sync anything to plex. more information here #108

Hey @luigi311 ...

So sounds like @bexem 's issue is different that mine.

I tested the :fixes and getting the exact same issue. 
Here's what I did:

- Updated to :fixes
- Ran test and was successful. (this is with no "real name" set in Plex)
- Changed my "real name" back to **Devante Weary** in Plex.
- Ran test and was unsuccessful. Same issue as above.

And to make sure my issue wasn't the same as in #108 , I removed my "full name", marked something as Watched in JF, and ran the test. That was successful and it showed up as Watched in Plex. However, adding my "full name" back again caused the original issue.

I know I'm repeating myself but it's like for some reason all of a sudden it's matching against the full name **IF** you have something in the full name field. When before it wasn't doing that.

**Comment by kariudo** [comment] 2024-01-24 20:46
I appear to be having more or less the same issue, interestingly only for certain episodes. maybe a few dozen show like this as marked every time it runs (after the initial run of probably 20k entries in history moving over).

log: https://gist.github.com/kariudo/c83384c8b042d53091b1cf741cacccb6

I have a 2 users, `kariudo` (realname in plex: "Hunter") and `amanda`, and a map set for hunter:kariudo.

Jellyfin had scanned the libraries to match, but had 0 watch history thus far.

The initial sync of years of history succeeded after a few hours, now every loop i see just this handful of stuff, i have not removed my "real name" from plex to see if that changes the behavior. These things it keeps syncing should be several years old in the watch history.

**Comment by luckycold** [comment] 2024-01-24 20:51
> I appear to be having more or less the same issue, interestingly only for certain episodes. maybe a few dozen show like this as marked every time it runs (after the initial run of probably 20k entries in history moving over).
> 
> log: https://gist.github.com/kariudo/c83384c8b042d53091b1cf741cacccb6
> 
> I have a 2 users, `kariudo` ("Full Name" in plex: "Hunter") and `amanda`, and a map set for hunter:kariudo. I had to set the map to prevent it saying "Hunter" did not exist in Jellyfin, even though both servers actually have `kariudo` as my username.
> 
> Jellyfin had scanned the libraries to match, but had 0 watch history thus far.
> 
> The initial sync of years of history succeeded after a few hours, now every loop i see just this handful of stuff, i have not removed my "full name" from plex to see if that changes the behavior. These things it keeps syncing should be several years old in the watch history.

I tested removing the real name on my own profile and I can confirm it fixed it for me when I had a similar issue.

**Comment by kariudo** [comment] 2024-01-24 22:44
It would appear that for me removing the full name had no effect, the same few dozen old history items still seem to be `[Mark]`

**Comment by kariudo** [comment] 2024-01-25 21:30
> It would appear that for me removing the full name had no effect, the same few dozen old history items still seem to be `[Mark]`

Found the problem I was having, I will leave my comments here in case someone else experiences the same:
Jellyfin tried to continually mark the episodes as match in Plex, since it knows the files were there for those episodes that plex told it were watched already in the first place (so it knew they existed correctly at some point) and that the match should be found; however, the horrifically bad Plex TV Series matcher was (despite flawless non-ambiguous and correctly named and organized media in series folders) matching random episodes from later seasons of the two series in question as episodes in the first seasons of the shows, causing it to not ever update. These definitly were formally correctly listed since the history was there was history in plex to make it to jellyfin in the first place for it to be trying to sync back.

Anywho, this was fixed in my edge case by pedantic adding of `.plexmatch` files for these two series to force it to repect a folder called "Season 3" as season 3... So in case anyone sees similar weirdness like this that the Full Name doesnt correct, double check that plex is seeing all the epsidoes correctly still for those old series, since they must have made a breaking change at some point with their scanner.

**Closed** 2024-01-26 00:53 UTC

**Comment by luigi311** [comment] 2024-01-26 01:04
Looks like i lost a change i made before. I reimplemented the fix so it uses usernames and falls back to full names such as for managed accounts. Give it another test and open the issue if there are still issues with it.
