### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by shedman214** [luigi311/JellyPlex-Watched#122] opened 2023-12-09 13:21 UTC
I have entered everything correctly and I'm getting a error. Not understanding what the error is? 
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/9beab6f9-bed2-4ae3-a0ad-234c94b4b6d6)

**Comment by luigi311** [comment] 2023-12-10 17:00
looks like a duplicate of #110, also do not remove the entire template when you are filing bugs, the template is there to provide information.

**Closed by luigi311** 2023-12-10 17:00 UTC

**Comment by shedman214** [comment] 2023-12-16 06:45
> looks like a duplicate of #110, also do not remove the entire template when you are filing bugs, the template is there to provide information.

Is this correct for mapping?? What duplicate is it creating? I'm using unraid
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/1f4845c0-2f31-437c-a111-77a676c36ef5)

**Comment by luigi311** [comment] 2023-12-16 10:18
Duplicate meaning there is already a ticket for this issue. That is not correct, Use { "Shows": "Anime", "Movie": "Anime Movies" } same for all the other mappings like user mappings

**Comment by shedman214** [comment] 2023-12-19 05:48
I have updated the info and I still get the same error in my logs. 
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/37978c91-14d2-433c-b5d7-544c693144b3)
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/49f8b2be-7c11-49dd-be44-902ad3287809)

**Comment by luigi311** [comment] 2023-12-19 06:20
Your user mapping is wrong, you are missing quotes after blackanimeking
{"BlackAnimeKing": "animeking1987"}

**Comment by shedman214** [comment] 2023-12-19 14:34
Error message for verify code? 
![image](https://github.com/luigi311/JellyPlex-Watched/assets/32603273/fb029b67-dc49-4447-bba6-5fc6f77b19db)

**Comment by luigi311** [comment] 2023-12-19 19:05
If you have 2FA i think the only easy way is to use a token instead of username and password
